GEMINI_API_KEY="AIzaSyCj8iQOcrolQlDI0jvdDmZ0jadxt1ywqWM"

[firebase_client]
"apiKey"="AIzaSyAE87OVYeYRqpecbeABvpqZxwCGbP6lriA"
"authDomain"="streamlit-web-app-8a99a.firebaseapp.com"
"projectId"="streamlit-web-app-8a99a"
"storageBucket"="streamlit-web-app-8a99a.firebasestorage.app"
"messagingSenderId"="840895928681"
"appId"="1:840895928681:web:b4954e48867fa382a205f8"
"measurementId"="G-JZKPKQHFLR"
"databaseURL"="https://streamlit-web-app-8a99a-default-rtdb.asia-southeast1.firebasedatabase.app/"

[firebase_admin]
"type"="service_account"
"project_id"="streamlit-web-app-8a99a"
"private_key_id"="007b8ade697da7f1978e5dcdeced43f8348cf43d"
"private_key"="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMnzj7Q+pFx6hg\nrkFVLgjMzO1jz4e/o4pYk3jlKiKmrvhF1E0dmwyq0t4tlvhuDjoknR6hq0mKvhyX\nr3WePiHDx4yrx/K9U3w2B/xLkgqvLsYgkFs78UbelIcR4XrnX9tNy03lFBAs6k3e\n8a8U7VIH+g1lneBStweeMZxf1nMdxc9REtmvOyCGkS+c+1ePX6UMrZieiUPeVfxB\npINvgDpQCMmEG6mKdrMK5zb3GRAmLKiVOWGy8BXh+y+dUJGc+331AMh60DqLUfRc\nYUgj7HRfgCw67C09kXI13iHOuqT7EFKIo+wBgAr71hHnEDUSG2NEubRqnznulQi9\nke455xczAgMBAAECggEAJISF9tG4DZwEQLzYjAsbJvGrrBRtdZYKKqSm/r72UCkJ\nxeyNlqsFJ7daT2iSDZIcbkxcGx4mkcw77hYyN3t/KyGByWZ1u7QahsoGDLaTkZAX\na9hXb+svaqm3MUm8VW6WBNwzmp5qBJoMK62WQXXZHfNSUMBMOHbRtTnFXpU3FijV\njtoBAzVa5FhCj3h41sNLqQSzf+p+67ZGtJRjzOmSXq58INRgjjSece4+V43HAKQk\nQMMU4PCqGjVoVFUtfsowD6VJBJVw4bXHBBoahdoTCo12beESZlxUL62e2UmNCDgp\nX8ASCZlLtcaWu9OrT8UNiZt5OcmFR6VA4RrxgBokgQKBgQDqw3qX4QsqKxmYW7m6\nqE/bDFnd+aviAJ3lVfePdTvnAtj7lFJqPHI60HYHEnHjfjTsUh7V6HYxiYuD3FAf\ndCY+2CdjcyDIiYDu6412b6EN5vryrjxJpvABEon9uh7/CSYuUUJrGS68Rgd9Kpon\nS9x6ZX3FC4XbYf9J+/VvfsaPBQKBgQDfIb27YzxC1wVF1o1s8PO4OLPC8qd55PWs\nOHpXDqLlgbLlELHA0vtwB7wgAc4ULSbn7jGJQF+8Lx9rGlvPOizSrx4yCMUJ1vIZ\niVE5BApq7BO8oNW0f4t/lXS+BQPe/VuStT9+mDkG8D2sJaUs3g09TQBWkR5K6YJM\nGZqv3j4y1wKBgB4tEk0DeFPrRlb3M2By0hDt/X8y4I0kVydrbW7bOt/u1cVAw3c0\nXdqBgSpXjJwZVOQrihskzkx/yZchcosYevIJBscZvVUJl7EeRgi7QJBw6EDZdJZj\nBuacY3BhxCo0GtxJRahOjFtXBQ9psnbqoWR6NzhkysfwSMhRwrKaMRuhAoGAKwLd\nCPcbEaNTH+A4yMw1nshHVofh4qxQ8w67/nYSznzO2Dr8mLfSwgirqdvPNrJxcnnG\n0Lc4/RR0UPf2xJ5pL3+UKX7pRHlLl8KRhpUR0QSK1WyHZVDEuiY8J7jdwylBcqk/\ngQ6kx4Kd0MY87cYr9SoXq5gzp6sVc8fnuojzomcCgYEAoyjh10xazu0TH7M5HBdJ\nM3Si5ZTVum8cQ/wKGFpGq2cA5rhqm+i8a9AMOtWwZ0iUlu64ZGUS4rrfKG2nLHBA\nfVaRYkke6q0YIdM2leK/1y9fmpIKQ7q+BdcAN4jegq9UYl4Ior5jn2QUjpp8C3F/\nJE3dmqmrCmS8fmzBGHv+sUE=\n-----END PRIVATE KEY-----\n"
"client_email"="firebase-adminsdk-fbsvc@streamlit-web-app-8a99a.iam.gserviceaccount.com"
"client_id"="104539451913234922081"
"auth_uri"="https://accounts.google.com/o/oauth2/auth"
"token_uri"="https://oauth2.googleapis.com/token"
"auth_provider_x509_cert_url"="https://www.googleapis.com/oauth2/v1/certs"
"client_x509_cert_url"="https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40streamlit-web-app-8a99a.iam.gserviceaccount.com"
"universe_domain"="googleapis.com"

